services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: therapist-env
  
  streamlit:
    image: therapist-env
    working_dir: /app
    ports:
      - "8501:8501"
    environment:
      MYSQL_HOST: sql_db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: mydatabase
    command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0
  
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
  
  sql_db:
    image: mysql:8.0
    volumes:
      - sql-data-db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
  
volumes:
  ollama:
  sql-data-db:
